image: node:latest

stages:
  - build
  - package

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

package-and-deploy:
  stage: package
  image: alpine:latest
  needs: ["build"]
  script:
    - apk add zip
    - zip -r decipher-extension.zip dist/
  artifacts:
    paths:
      - decipher-extension.zip
  only:
    - main
